## Arrays

In [2]:

# import required libraries
import numpy as np
from numpy.linalg import norm
 
# define two lists or array
A = np.array([2,1,2,3,2,9])
B = np.array([3,4,2,4,5,5])
 
print("A:", A)
print("B:", B)

A: [2 1 2 3 2 9]
B: [3 4 2 4 5 5]


In [3]:
# compute cosine similarity
cosine = np.dot(A,B)/(norm(A)*norm(B))
print("Cosine Similarity:", cosine)

Cosine Similarity: 0.8188504723485274


## Matrix

In [5]:
A = np.array([[2,1,2],
              [4,6,8],
              [9,6,5]])
B = np.array([[3,4,2],
              [1,2,3],
              [3,0,8]])
print("A:\n", A)
print("B:\n", B)

A:
 [[2 1 2]
 [4 6 8]
 [9 6 5]]
B:
 [[3 4 2]
 [1 2 3]
 [3 0 8]]


In [7]:
# compute cosine similarity
cosine = np.sum(A*B, axis=1)/(norm(A, axis=1)*norm(B, axis=1))
print("cosine similarity:",cosine)

cosine similarity: [0.86657824 0.99258333 0.65806562]
